name = "MyPhD"
uuid = "4ea3a064-0e8b-455b-8496-7d11cdb2f699"  # Generate a unique UUID using `using UUIDs; UUIDs.uuid4()`
authors = ["Ranjit Patnaik <ranjitpatnaik@giet.edu>"]
version = "0.1.0"

[deps]

